name: remalux_ar
description: "A new Flutter project."

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  storybook_flutter: ^0.14.1
  flutter_riverpod: ^2.6.1
  go_router: ^14.4.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  firebase_analytics: ^11.3.4
  http: ^1.2.2
  file_picker: ^8.1.4
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  dio: ^5.7.0
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.16
  intl: ^0.19.0
  flutter_masked_text2: ^0.9.1
  story: ^1.1.0
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.10
  flutter_datetime_picker: ^1.5.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4
  yandex_mapkit: ^4.1.0
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  local_auth: ^2.1.8
  dots_indicator: ^3.0.0
  amplitude_flutter: ^3.13.0
  shimmer: ^3.0.0
  chucker_flutter: ^1.8.3
  flutter_html: ^3.0.0
  mask_text_input_formatter: ^2.9.0
  google_maps_flutter: ^2.10.1
  easy_localization: ^3.0.5
  flutter_local_notifications: ^19.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/core/assets/icons/
    - lib/core/assets/icons/doctors/
    - lib/core/assets/icons/tabs/
    - lib/core/assets/icons/selector/
    - lib/core/assets/icons/sections/
    - lib/core/assets/icons/profile/
    - lib/core/assets/images/
    - lib/core/assets/icons/blobs/
    - lib/core/assets/images/logos/
    - lib/core/assets/images/onboarding/
    - lib/core/assets/pdf/
    - lib/core/assets/translations/
    - lib/core/assets/images/colors/
    - lib/core/assets/images/store/
    - lib/core/assets/images/partnership/
    - lib/core/assets/images/part_prods/
    - lib/core/assets/icons/cart/

  # Fonts будут добавлены позже
  # fonts:
  #   - family: Ysabeau
  #     fonts:
  #       - asset: lib/core/assets/fonts/Ysabeau-Regular.ttf
  #         weight: 400
  #       - asset: lib/core/assets/fonts/Ysabeau-Italic.ttf
  #         weight: 400
  #         style: italic
  #       - asset: lib/core/assets/fonts/Ysabeau-Light.ttf
  #         weight: 300
  #       - asset: lib/core/assets/fonts/Ysabeau-LightItalic.ttf
  #         weight: 300
  #         style: italic
  #       - asset: lib/core/assets/fonts/Ysabeau-ExtraLight.ttf
  #         weight: 200
  #       - asset: lib/core/assets/fonts/Ysabeau-ExtraLightItalic.ttf
  #         weight: 200
  #         style: italic
  #       - asset: lib/core/assets/fonts/Ysabeau-Medium.ttf
  #         weight: 500
  #       - asset: lib/core/assets/fonts/Ysabeau-MediumItalic.ttf
  #         weight: 500
  #         style: italic
  #       - asset: lib/core/assets/fonts/Ysabeau-SemiBold.ttf
  #         weight: 600
  #       - asset: lib/core/assets/fonts/Ysabeau-SemiBoldItalic.ttf
  #         weight: 600
  #         style: italic
  #       - asset: lib/core/assets/fonts/Ysabeau-Bold.ttf
  #         weight: 700
  #       - asset: lib/core/assets/fonts/Ysabeau-BoldItalic.ttf
  #         weight: 700
  #         style: italic
  #       - asset: lib/core/assets/fonts/Ysabeau-ExtraBold.ttf
  #         weight: 800
  #       - asset: lib/core/assets/fonts/Ysabeau-ExtraBoldItalic.ttf
  #         weight: 800
  #         style: italic
  #       - asset: lib/core/assets/fonts/Ysabeau-Black.ttf
  #         weight: 900
  #       - asset: lib/core/assets/fonts/Ysabeau-BlackItalic.ttf
  #         weight: 900
  #         style: italic
  #       - asset: lib/core/assets/fonts/Ysabeau-Thin.ttf
  #         weight: 100
  #       - asset: lib/core/assets/fonts/Ysabeau-ThinItalic.ttf
  #         weight: 100
  #         style: italic

  #   - family: YsabeauInfant
  #     fonts:
  #       - asset: lib/core/assets/fonts/YsabeauInfant-Regular.ttf
  #         weight: 400
  #       - asset: lib/core/assets/fonts/YsabeauInfant-Bold.ttf
  #         weight: 700
  #       - asset: lib/core/assets/fonts/YsabeauInfant-SemiBold.ttf
  #         weight: 600
