name: remalux_ar
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  storybook_flutter: ^0.14.1
  flutter_riverpod: ^2.6.1
  go_router: ^14.4.0
  firebase_core: ^3.7.0
  firebase_messaging: ^15.1.4
  firebase_analytics: ^11.3.4
  http: ^1.2.2
  file_picker: ^8.1.4
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  dio: ^5.7.0
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.16
  intl: ^0.19.0
  flutter_masked_text2: ^0.9.1
  story: ^1.1.0
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.10
  flutter_datetime_picker: ^1.5.1
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  yandex_mapkit: ^3.4.0
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  local_auth: ^2.1.8
  dots_indicator: ^3.0.0
  amplitude_flutter: ^3.13.0
  shimmer: ^3.0.0
  chucker_flutter: ^1.8.3
  flutter_html: ^3.0.0-beta.2
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/core/assets/icons/
    - lib/core/assets/icons/doctors/
    - lib/core/assets/icons/tabs/
    - lib/core/assets/icons/selector/
    - lib/core/assets/icons/sections/
    - lib/core/assets/icons/profile/
    - lib/core/assets/images/
    - lib/core/assets/icons/blobs/
    - lib/core/assets/images/logos/
    - lib/core/assets/images/onboarding/
    - lib/core/assets/pdf/
    - lib/core/assets/images/colors/
    - lib/core/assets/images/store/
